### ISSUE TITLE
No module named "Selenium"

### ISSUE THREAD

**Issue by R2kReigns** [markmelnic/reddit-bot#1]
![Screenshot (406)](https://user-images.githubusercontent.com/97167010/149611270-eb9d8aaa-ec2d-4a1e-a3cc-c0128e573079.png)

How to solve this? 
Also where to enter the credentials?

**Comment by markmelnic** [comment]
Please read the usage section of README.md

First install requirements:
`
pip install -r requirements.txt
`    
Then download the chrome webdriver here [https://chromedriver.chromium.org/downloads](https://chromedriver.chromium.org/downloads)

Now to use run:
`
py main.py -u username -p password --url https://www.reddit.com_link_to_post --action 1
` 

Read the documentation for more advanced options.
