### ISSUE TITLE
Question/Proxies

### ISSUE THREAD

**Issue by nidark** [markmelnic/reddit-bot#3]
I believe reddit does not count upvotes from the same IP, do they ?

PS: 
Using proxies might be an option.
Here they give free proxies https://proxy2.webshare.io/
Proxy:port:user:pasword

**Comment by markmelnic** [comment]
They count upvotes from the accounts that upvoted a post. The only thing proxies could help with is prevent reddit from blocking bot activity due to multiple accounts using the same IP in a short timespan.

**Comment by nidark** [comment]
Ah. interesting. Thank you!
