### ISSUE TITLE
Ghosting

### ISSUE THREAD

**Issue by britcanamedia** [markmelnic/reddit-bot#8]
I am having a real issue getting past the ghosting when commenting on posts. We're talking about NON spam posts, completely on topic with the current conversation and it just vanishes like a shadow ban, yet the account is still fine for real browser session posts. I've tried routing and binding through legit residential IP space, proxies, user behaviour movements, amazon aws IPs, new accounts old accounts, nothing is working. I must be missing something. Any tips you may have tried that I haven't would be greatly appreciated my friend. This is messing with my day LOL.

Cheers,
wuzzy

**Comment by britcanamedia** [comment]
After dumping the page I can now see that the comment text box just never appears, no matter how long I wait and how much "user behaviour" I do...  I am 100% logged in. So that would explain the issue. Hmmmmm

**Comment by britcanamedia** [comment]
It was clearing the browser data. I thank you for your code it really helped. Question, how come you're not using **kwargs for your bot __init__, that way if you're utilizing threading on 1000s of accounts it would make the process I think much smoother. Either way, great job. Hats off to you.

**Comment by markmelnic** [comment]
Hey there, thanks for reaching out )

Glad you figured everything out. I guess there are not that many args yet so explicitly using them does not seem problematic (just yet). As for threading, I thought about integrating threading but that messes with selenium sometimes. For example focusing on another window will execute interactions from another thread, so you would need multiple chromium instances open which 1st isn't optimal for hardware performance, 2nd Reddit spots multiple accounts logged in at the same time from the same IP address. And while there are solutions to possibly any problem, this worked for me and wasn't highly requested (lol), so I called it a day as is.

If you feel like there is a thing that will certainly improve the code, let me know, or open a PR.

Cheers mate

**Comment by markmelnic** [comment]
P.S. Check out this discussion if you've got the time [Links & Accounts, txt files, csv, json or all #7](https://github.com/markmelnic/reddit-bot/discussions/7)
